
const jobs = [
    {
        id: 1,
        title: "SDE Intern",
        company: "Flipkart",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "DSA", "Problem Solving"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹40k–₹80k/month Internship",
        applyUrl: "https://www.flipkartcareers.com/",
        description: "Join Flipkart's engineering team as an SDE Intern. You will work on scalable backend systems and solve complex e-commerce problems. Strong knowledge of Data Structures and Algorithms is required."
    },
    {
        id: 2,
        title: "Junior Backend Developer",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Node.js", "Express", "MongoDB"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        applyUrl: "https://paytm.com/careers",
        description: "Paytm is looking for a Junior Backend Developer to build robust APIs for our payments platform. Experience with Node.js and database management is essential."
    },
    {
        id: 3,
        title: "Frontend Developer",
        company: "Razorpay",
        location: "Bengaluru",
        mode: "Remote",
        experience: "1-3",
        skills: ["React.js", "Redux", "CSS3"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "12–18 LPA",
        applyUrl: "https://razorpay.com/jobs",
        description: "Craft beautiful and responsive payment interfaces at Razorpay. We are seeking a Frontend Developer with a keen eye for design and performance optimization."
    },
    {
        id: 4,
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C++", "Python", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://www.tcs.com/careers",
        description: "Start your career with TCS as a GET. You will undergo rigorous training and work on enterprise-level projects across various domains."
    },
    {
        id: 5,
        title: "Java Developer",
        company: "Infosys",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "Microservices"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "5–8 LPA",
        applyUrl: "https://www.infosys.com/careers",
        description: "Infosys is hiring Java Developers to design and implement microservices-based architecture. Proficiency in Spring Boot and REST APIs is a must."
    },
    {
        id: 6,
        title: "Data Analyst Intern",
        company: "Swiggy",
        location: "Bengaluru",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "SQL", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹35k/month Internship",
        applyUrl: "https://careers.swiggy.com/",
        description: "Analyze food delivery trends and customer behavior at Swiggy. Strong SQL skills and ability to visualize data are required for this internship."
    },
    {
        id: 7,
        title: "Full Stack Engineer",
        company: "CRED",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Go", "AWS"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "18–25 LPA",
        applyUrl: "https://careers.cred.club/",
        description: "Join CRED's high-performance team. We are looking for engineers who can build scalable frontend and backend systems. Experience with Go is a plus."
    },
    {
        id: 8,
        title: "Software Engineer",
        company: "Google",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["C++", "System Design", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "20–35 LPA",
        applyUrl: "https://careers.google.com/",
        description: "Google India is hiring Software Engineers to work on world-class products. Demonstrate your algorithmic thinking and system design skills."
    },
    {
        id: 9,
        title: "React Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["React.js", "JavaScript", "HTML5"],
        source: "Zoho Careers",
        postedDaysAgo: 6,
        salaryRange: "6–9 LPA",
        applyUrl: "https://www.zoho.com/careers/",
        description: "Build simplified SaaS applications at Zoho. We are looking for developers who can write clean, maintainable React code."
    },
    {
        id: 10,
        title: "App Developer",
        company: "PhonePe",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kotlin", "Android", "Java"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "15–22 LPA",
        applyUrl: "https://www.phonepe.com/careers/",
        description: "Develop seamless UPI payment experiences at PhonePe. Expertise in Android development with Kotlin is required."
    },
    {
        id: 11,
        title: "System Engineer",
        company: "Wipro",
        location: "Kolkata",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "OS Concepts", "Networking"],
        source: "Campus",
        postedDaysAgo: 7,
        salaryRange: "3.5 LPA",
        applyUrl: "https://careers.wipro.com/",
        description: "Wipro's Project Engineer program offers a great starting point for fresh graduates. Work on critical IT infrastructure and applications."
    },
    {
        id: 12,
        title: "QA Automation Engineer",
        company: "Accenture",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Selenium", "Java", "TestNG"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "6–10 LPA",
        applyUrl: "https://www.accenture.com/in-en/careers",
        description: "Ensure software quality through automated testing. Experience with Selenium and building test frameworks is essential."
    },
    {
        id: 13,
        title: "Python Developer",
        company: "IBM",
        location: "Bengaluru",
        mode: "Remote",
        experience: "0-1",
        skills: ["Python", "Django", "Cloud"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "7–11 LPA",
        applyUrl: "https://www.ibm.com/in-en/employment/",
        description: "Develop cloud-native applications using Python at IBM. Familiarity with IBM Cloud or AWS is a differentiator."
    },
    {
        id: 14,
        title: "Intern - Software Engineering",
        company: "Cisco",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Networking", "C", "Python"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "₹50k/month Internship",
        applyUrl: "https://jobs.cisco.com/",
        description: "Work on the future of networking at Cisco. Strong C programming skills and understanding of TCP/IP are required."
    },
    {
        id: 15,
        title: "Associate Consultant",
        company: "Capgemini",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "SQL", "Agile"],
        source: "LinkedIn",
        postedDaysAgo: 8,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.capgemini.com/in-en/careers/",
        description: "Join Capgemini as an Associate Consultant. You will work in agile teams to deliver high-quality software solutions."
    },
    {
        id: 16,
        title: "UI/UX Designer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Figma", "Sketch", "Prototyping"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–16 LPA",
        applyUrl: "https://www.freshworks.com/company/careers/",
        description: "Design delightful user experiences for enterprise software at Freshworks. A strong portfolio showcasing UI design is mandatory."
    },
    {
        id: 17,
        title: "DevOps Engineer",
        company: "Zomato",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Docker", "Kubernetes", "AWS"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "12–20 LPA",
        applyUrl: "https://www.zomato.com/careers",
        description: "Manage and scale Zomato's infrastructure. Experience with containerization and CI/CD pipelines is key."
    },
    {
        id: 18,
        title: "Analyst",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Excel", "Tableau", "Analytics"],
        source: "Campus",
        postedDaysAgo: 9,
        salaryRange: "6–9 LPA",
        applyUrl: "https://www2.deloitte.com/in/en/careers.html",
        description: "Deloitte is hiring analysts for their consulting wing. Strong analytical skills and proficiency in data tools are required."
    },
    {
        id: 19,
        title: "Software Developer",
        company: "Oracle",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "PL/SQL", "Cloud"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "14–22 LPA",
        applyUrl: "https://www.oracle.com/in/corporate/careers/",
        description: "Work on Oracle's cloud infrastructure projects. Deep understanding of databases and Java programming is essential."
    },
    {
        id: 20,
        title: "Product Intern",
        company: "Meesho",
        location: "Bengaluru",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Product Thinking", "Analytics", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://www.meesho.io/careers",
        description: "Help shape the future of e-commerce for Bharat. Meesho is looking for product interns with a data-driven mindset."
    },
    {
        id: 21,
        title: "Dotnet Developer",
        company: "HCL Tech",
        location: "Noida",
        mode: "Onsite",
        experience: "3-5",
        skills: [".NET Core", "C#", "Azure"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "7–12 LPA",
        applyUrl: "https://www.hcltech.com/careers",
        description: "Senior Dotnet Developer needed for legacy modernization projects. Experience with Azure cloud services is preferred."
    },
    {
        id: 22,
        title: "React Native Developer",
        company: "Juspay",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React Native", "Redux", "Mobile Dev"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–25 LPA",
        applyUrl: "https://juspay.in/careers",
        description: "Build high-performance mobile payment SDKs at Juspay. We value deep understanding of functional programming."
    },
    {
        id: 23,
        title: "Business Analyst",
        company: "Mu Sigma",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Statistics", "R", "Python"],
        source: "Campus",
        postedDaysAgo: 6,
        salaryRange: "5–5.5 LPA",
        applyUrl: "https://www.mu-sigma.com/careers",
        description: "Solve complex business problems using math and data. Mu Sigma's training program is rigorous and rewarding."
    },
    {
        id: 24,
        title: "Cloud Support Engineer",
        company: "Amazon Web Services",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Linux", "Networking", "AWS"],
        source: "Amazon Jobs",
        postedDaysAgo: 2,
        salaryRange: "12–16 LPA",
        applyUrl: "https://www.amazon.jobs/en",
        description: "Provide technical support for AWS customers. Strong Linux and networking fundamentals are required."
    },
    {
        id: 25,
        title: "Frontend Engineer",
        company: "Groww",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "TypeScript", "Performance"],
        source: "Instahyre",
        postedDaysAgo: 1,
        salaryRange: "18–28 LPA",
        applyUrl: "https://groww.in/careers",
        description: "Simplify investing for millions. Groww needs frontend engineers who obsess over performance and user experience."
    },
    {
        id: 26,
        title: "Java Developer",
        company: "Mindtree",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Java", "Spring", "Hibernate"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "8–14 LPA",
        applyUrl: "https://www.mindtree.com/careers",
        description: "Join Mindtree's digital transformation team. Looking for experienced Java developers with strong backend skills."
    },
    {
        id: 27,
        title: "SDE-1",
        company: "ShareChat",
        location: "Bengaluru",
        mode: "Remote",
        experience: "0-1",
        skills: ["Golang", "Microservices", "NoSQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "16–24 LPA",
        applyUrl: "https://sharechat.com/careers",
        description: "Build scalable social media features for ShareChat. Experience with Go and high-concurrency systems is a plus."
    },
    {
        id: 28,
        title: "Technical Support",
        company: "Dell",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Hardware", "Troubleshooting", "Communication"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "3–4.5 LPA",
        applyUrl: "https://jobs.dell.com/",
        description: "Dell is hiring for technical support roles. Good communication skills and hardware knowledge are needed."
    },
    {
        id: 29,
        title: "Machine Learning Engineer",
        company: "Myntra",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "TensorFlow", "NLP"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "20–30 LPA",
        applyUrl: "https://careers.myntra.com/",
        description: "Apply ML to fashion e-commerce. Work on recommendation engines and visual search at Myntra."
    },
    {
        id: 30,
        title: "PHP Developer",
        company: "Tech Mahindra",
        location: "Pune",
        mode: "Onsite",
        experience: "1-3",
        skills: ["PHP", "Laravel", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "4–7 LPA",
        applyUrl: "https://careers.techmahindra.com/",
        description: "Maintain and develop legacy web applications. Proficiency in PHP frameworks like Laravel is required."
    },
    {
        id: 31,
        title: "iOS Developer",
        company: "MakeMyTrip",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Swift", "iOS SDK", "Xcode"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "14–20 LPA",
        applyUrl: "https://www.makemytrip.com/careers/",
        description: "Build the best travel app in India. We need iOS developers with a passion for mobile UI and performance."
    },
    {
        id: 32,
        title: "Cyber Security Analyst",
        company: "PwC India",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Network Security", "Ethical Hacking", "Audit"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "8–12 LPA",
        applyUrl: "https://www.pwc.in/careers.html",
        description: "Protect enterprise assets as a security analyst at PwC. Certifications like CEH or CISSP are preferred."
    },
    {
        id: 33,
        title: "SAP Consultant",
        company: "SAP Labs",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["ABAP", "HANA", "SAP UI5"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "12–18 LPA",
        applyUrl: "https://www.sap.com/india/about/careers.html",
        description: "SAP Labs is hiring experienced consultants for their ERP solutions. Deep knowledge of ABAP is required."
    },
    {
        id: 34,
        title: "Blockchain Developer",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "0-1",
        skills: ["Solidity", "Ethereum", "Web3.js"],
        source: "Web3 Careers",
        postedDaysAgo: 1,
        salaryRange: "15–25 LPA",
        applyUrl: "https://polygon.technology/careers",
        description: "Work on the leading Layer-2 scaling solution. Solidity development experience is crucial."
    },
    {
        id: 35,
        title: "Marketing Analyst",
        company: "Nykaa",
        location: "Mumbai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Google Analytics", "Excel", "Marketing"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "5–8 LPA",
        applyUrl: "https://www.nykaa.com/careers",
        description: "Analyze marketing campaigns and growth metrics for Nykaa. Data-driven mindset is key."
    },
    {
        id: 36,
        title: "Graduate Trainee",
        company: "L&T Infotech",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL"],
        source: "Campus",
        postedDaysAgo: 8,
        salaryRange: "3.5–4 LPA",
        applyUrl: "https://www.lntinfotech.com/careers/",
        description: "LTI is hiring fresh graduates for their training program. Good academic record and logic skills needed."
    },
    {
        id: 37,
        title: "Angular Developer",
        company: "Genpact",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Angular", "TypeScript", "RxJS"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "6–10 LPA",
        applyUrl: "https://www.genpact.com/careers",
        description: "Frontend developer needed for enterprise web apps. Strong Angular 8+ experience required."
    },
    {
        id: 38,
        title: "Product Designer",
        company: "Urban Company",
        location: "Gurugram",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Figma", "User Research", "Interaction Design"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–18 LPA",
        applyUrl: "https://www.urbancompany.com/careers",
        description: "Design service experiences for Urban Company. We value empathy and pixel-perfection."
    },
    {
        id: 39,
        title: "Data Engineer",
        company: "Ola",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Spark", "Hadoop", "Scala"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "15–22 LPA",
        applyUrl: "https://olacabs.com/careers",
        description: "Build data pipelines for Ola's ride-hailing/EV business. Experience with Big Data stack is mandatory."
    },
    {
        id: 40,
        title: "Embedded Engineer",
        company: "Qualcomm",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["C", "RTOS", "Microcontrollers"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "14–20 LPA",
        applyUrl: "https://www.qualcomm.com/company/careers",
        description: "Work on 5G and chipset firmware at Qualcomm. Strong low-level C programming skills required."
    },
    {
        id: 41,
        title: "Ruby on Rails Developer",
        company: "Gojek",
        location: "Bengaluru",
        mode: "Remote",
        experience: "3-5",
        skills: ["Ruby", "Rails", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "25–35 LPA",
        applyUrl: "https://www.gojek.io/careers",
        description: "Senior developer needed for Gojek's SuperApp. Scaling Rails applications is the primary challenge."
    },
    {
        id: 42,
        title: "QA Tester",
        company: "HDFC Bank",
        location: "Mumbai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Manual Testing", "Banking Domain", "SQL"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.hdfcbank.com/personal/about-us/careers",
        description: "QA role for HDFC's netbanking applications. Domain knowledge in banking is a plus."
    },
    {
        id: 43,
        title: "Game Developer",
        company: "Dream11",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Unity", "C#", "Multiplayer"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–22 LPA",
        applyUrl: "https://about.dream11.com/careers",
        description: "Create engaging sports gaming experiences. Unity and C# proficiency is required."
    },
    {
        id: 44,
        title: "Salesforce Developer",
        company: "Salesforce",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Apex", "Lightning", "CRM"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "12–18 LPA",
        applyUrl: "https://www.salesforce.com/in/company/careers/",
        description: "Develop custom solutions on the Salesforce platform. Certification in PD1/PD2 is preferred."
    },
    {
        id: 45,
        title: "Intern",
        company: "Adobe",
        location: "Noida",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["C++", "Algorithms", "OS"],
        source: "Campus",
        postedDaysAgo: 1,
        salaryRange: "₹60k/month Internship",
        applyUrl: "https://www.adobe.com/careers.html",
        description: "Research and development internship at Adobe. Work on Photoshop/Acrobat teams."
    },
    {
        id: 46,
        title: "Network Engineer",
        company: "Airtel",
        location: "Gurugram",
        mode: "Onsite",
        experience: "1-3",
        skills: ["CCNA", "Routing", "Switching"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "5–8 LPA",
        applyUrl: "https://www.airtel.in/careers/",
        description: "Manage Airtel's enterprise networks. CCNA certification is highly desirable."
    },
    {
        id: 47,
        title: "Content Reviewer",
        company: "Facebook (Meta)",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Communication", "Analytical Skills"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.metacareers.com/",
        description: "Review content to ensure platform safety. Language proficiency is important."
    },
    {
        id: 48,
        title: "RPA Developer",
        company: "UiPath",
        location: "Bengaluru",
        mode: "Remote",
        experience: "1-3",
        skills: ["UiPath", "Automation", ".NET"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–15 LPA",
        applyUrl: "https://www.uipath.com/company/careers",
        description: "Automate business processes using UiPath. Experience in building bots is required."
    },
    {
        id: 49,
        title: "Site Reliability Engineer",
        company: "LinkedIn",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Linux", "Troubleshooting"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "20–30 LPA",
        applyUrl: "https://careers.linkedin.com/",
        description: "Keep LinkedIn running smoothly. SRE role involving automation and incident management."
    },
    {
        id: 50,
        title: "Support Engineer",
        company: "Microsoft",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Azure", "Windows Server", "Powershell"],
        source: "Microsoft Careers",
        postedDaysAgo: 3,
        salaryRange: "12–16 LPA",
        applyUrl: "https://careers.microsoft.com/",
        description: "Support Microsoft's enterprise customers. Deep knowledge of Windows Server/Azure needed."
    },
    {
        id: 51,
        title: "React Developer",
        company: "Unacademy",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "CSS", "PWA"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "14–20 LPA",
        applyUrl: "https://unacademy.com/careers",
        description: "Building the future of education. React developers with a knack for UI needed."
    },
    {
        id: 52,
        title: "Python Intern",
        company: "Zerodha",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Postgres", "Trading domain"],
        source: "Zerodha Careers",
        postedDaysAgo: 0,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://zerodha.tech/careers",
        description: "Internship for FOSS enthusiasts. Work on Zerodha's trading infrastructure."
    },
    {
        id: 53,
        title: "Database Administrator",
        company: "Sopra Steria",
        location: "Noida",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Oracle DBA", "SQL Tuning", "Backup"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "8–12 LPA",
        applyUrl: "https://www.soprasteria.com/careers",
        description: "Senior DBA role. Manage large-scale Oracle databases for European clients."
    },
    {
        id: 54,
        title: "Flutter Developer",
        company: "Mamaearth",
        location: "Gurugram",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Flutter", "Dart", "Mobile"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–15 LPA",
        applyUrl: "https://mamaearth.in/careers",
        description: "Build Mamaearth's mobile app using Flutter. Experience with state management needed."
    },
    {
        id: 55,
        title: "Systems Analyst",
        company: "Sonata Software",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Requirements Gathering", "UML", "Documentation"],
        source: "JobPortal",
        postedDaysAgo: 6,
        salaryRange: "5–8 LPA",
        applyUrl: "https://www.sonata-software.com/careers",
        description: "Bridge the gap between business and IT. Analyst role for travel systems."
    },
    {
        id: 56,
        title: "Graphic Designer",
        company: "BookMyShow",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Photoshop", "Illustrator", "Creativity"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "4–6 LPA",
        applyUrl: "https://in.bookmyshow.com/careers",
        description: "Design social media creatives and event banners for BookMyShow."
    },
    {
        id: 57,
        title: "Technical Writer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["English", "Documentation", "Tech Savvy"],
        source: "Zoho Careers",
        postedDaysAgo: 4,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.zoho.com/careers/technical-writer",
        description: "Write clear and concise documentation for Zoho's software products."
    },
    {
        id: 58,
        title: "Operations Executive",
        company: "Dunzo",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Operations", "Logistics", "Excel"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3–4 LPA",
        applyUrl: "https://www.dunzo.com/careers",
        description: "Manage daily delivery operations. Requires quick thinking and problem solving."
    },
    {
        id: 59,
        title: "Front Office Executive",
        company: "Taj Hotels",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Communication", "Hospitality"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "3–4 LPA",
        applyUrl: "https://www.tajhotels.com/careers",
        description: "Guest relations role at Taj. Excellent communication skills required."
    },
    {
        id: 60,
        title: "HR Intern",
        company: "KPMG",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["HR", "Recruitment", "Communication"],
        source: "Campus",
        postedDaysAgo: 2,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://home.kpmg/in/en/home/careers.html",
        description: "Assist the HR team with recruitment drives and employee engagement activities."
    }
];
